### ISSUE TITLE
Add contribution Guide

### ISSUE THREAD

**Issue by devgenix** [faradayafrica/Url-Shortener-API#3]
Create a file name **contribution.md** and use this [template.](https://github.com/faradayafrica/Faraday-community/blob/main/contributing.md) 
Modify the link to the readme to point to the README file for this repo.

**Comment by mayankshukla94** [comment]
Can I pick this?

**Comment by mayankshukla94** [comment]
@devgenix I have raised this PR https://github.com/faradayafrica/Url-Shortener-API/pull/5
